//Copyright (c) 2026 Jung, Yoomin. All rights reserved.

#include <nds.h>
#include <fat.h>
#include <stdio.h>
#include "TitleScreen.hpp"
#include "Menu.hpp"
#include "Settings.hpp"
#include "Shop.hpp"
#include "video.h"
#include "Credits.h"
#include <maxmod9.h>
#include <time.h>
#include "common.h"
#include "Game.hpp" 
#include <string>
#include "bgm.h"
#include "save.h"
// Headers autogenerated when files are find inside AUDIODIRS in the Makefile
#include "soundbank.h"
#include "soundbank_bin.h"
// Header autogenerated for each PNG file inside GFXDIRS in the Makefile
#include "neon.h"
// Header autogenerated for each BIN file inside BINDIRS in the Makefile
#include "data_string_bin.h"
#include "Select.hpp"



int main(void) {
    //reduceHeapSize(0x20000);
    defaultExceptionHandler(); 
    System_Init();


    SaveData save;
    Save_InitNew(&save);
    /*
    bool init_ok = fatInitDefault();
    consoleDemoInit();
    if (!init_ok)
    {
         printf("fat init failed\n\n");
         Save_InitNew(&save);
    } else {
        printf("Checking save file...\n");

        if (Save_Read(&save))
        {
            printf("Existing save loaded!\n\n");
        }
        else
        {
            printf("No valid save found.\n");
            printf("Creating new save...\n\n");

            Save_InitNew(&save);

            if (!Save_Write(&save))
            {
                //ShowFatalError("Failed to create save file.");
                printf("Failed to create save file.\n\n");
            }
        }

        printf("Current Save Data:\n");
        printf("Level: %lu\n", save.level);
        printf("HP: %lu\n", save.hp);
        printf("Gold: %lu\n", save.gold);
        printf("Difficulty: %lu\n", save.difficulty);
        printf("\nPress START to save and exit.\n");

        while (1)
        {
            swiWaitForVBlank();
            scanKeys();

            if (keysDown() & KEY_START)
                break;
        }
    }
    */
    
    // --- Title Screen Phase ---
    TitleScreen title; 
    title.init();            // set up 2D top + 3D bottom      // initial render
    while (!title.isFinished()) {
        title.update();      // handle input + update camera 
        title.render();  
    }
    title.cleanUp();
    

    MainMenu menu;
    menu.seed = title.seed; 
    Settings settings;
    Shop shop; 
    StageSelect stageSelect; 
    
    // --- Main Game Phase ---
    while (1) {
        // --- Main Menu Phase ---
        menu.init(); //title.seed 
        while (!menu.isFinished()) {
            menu.update();
            menu.render();
        }
        menu.cleanUp();

        // --- Story Mode ---
        if (menu.selectedButton == 0) {
            stageSelect.exit = false;
            stageSelect.charStage = LEIA; 

            while (!stageSelect.exit) {
                if (save.level < 100){ 
                    stageSelect.unLockCharStage = LEIA; 
                    stageSelect.unLockStage = save.level; 
                } else if (save.level < 200) {
                    stageSelect.unLockCharStage = AIDEN; 
                    stageSelect.unLockStage = save.level - 100; 
                } else {
                    stageSelect.unLockCharStage = LINA; 
                    stageSelect.unLockStage = save.level - 200; 
                }
                // 현재 캐릭터에 맞는 이름 결정
                const char* name;
                if (stageSelect.charStage == LEIA)       name = "Leia";
                else if (stageSelect.charStage == AIDEN) name = "Aiden";
                else                               name = "Lina";

                stageSelect.init(name, stageSelect.charStage);
                while (!stageSelect.isFinished()) {
                    stageSelect.update();
                    stageSelect.render();
                }
                stageSelect.cleanUp();

                // exit stage select
                if (stageSelect.exit) {
                    break; // return to menu. 
                }

                // Pressed A to confirm stage
                if (stageSelect.getSelectedStage() > 0) {
                    Game game("player1", &save);
                    game.StartStage(stageSelect.charStage, stageSelect.getSelectedStage());
                }
            }
        }

        //--Endless phase -- 
        if (menu.selectedButton == 1){
            Game game("player1", &save); //username, damage, accuracy, criticalChance, criticalDamage
            if(save.difficulty == 0) game.StartStage(LINA, 0); 
            else if (save.difficulty == 1) game.StartStage(AIDEN, 0); 
            else game.StartStage(LEIA, 0); 
        }
        // --Shop phase -- 
        if (menu.selectedButton == 2){
            shop.Init(&save); 
            while(!shop.isFinished()){
                shop.Update();
            }
            shop.cleanUp(&save);
        }
        //-- Settings Phase ---
        if (menu.selectedButton == 3) {
            settings.init(&save);
            while (!settings.isFinished()) {
                settings.update();
                settings.draw();
            }
            settings.end(&save); 
        }

        if (menu.selectedButton == 4) {
            fatInitDefault();
            consoleDemoInit();
            //if (!Save_Write(&save))
            //{
               // ShowFatalError("Failed to save data.");
            //}

            consoleClear();
            printf("Game saved successfully!\n");
            printf("Press START to exit.\n");

            while (1)
            {
                swiWaitForVBlank();
                scanKeys();
                if (keysDown() & KEY_START)
                    break;
            }
        } 
        menu.selectedButton = 0; 
    }

    return 0;
}
